name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Android SDK components
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --update
        sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-30" \
          "build-tools;30.0.3" \
          "emulator" \
          "system-images;android-30;google_apis;x86_64"

    - name: Run emulator and instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        target: google_apis
        profile: pixel
        disable-animations: true
        emulator-options: -no-snapshot-save -noaudio -no-boot-anim
        script: |
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Waiting for emulator to boot... ($boot_completed)"
            sleep 5
          done
          ./gradlew connectedDebugAndroidTest
