name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60  # Gives emulator more time to shut down

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Download Android SDK Tools
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools-version: 30.0.3
        ndk-version: 21.4.7075529

    - name: Accept SDK licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Run instrumented tests on emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        target: google_apis
        profile: pixel
        disable-animations: true
        emulator-options: -no-snapshot-save -noaudio -no-boot-anim
        script: ./gradlew connectedDebugAndroidTest
